### ISSUE TITLE
can you crawl social.wake.st

### ISSUE THREAD

**Issue by wakest** [brortao/fediverse.space#28]
its my personal instance which is proved on my profile by rel=me at social.wake.st/@wakest

thank you! excited to see this project, I just ran into it. I was the first one (to my knowledge) to try to make an interactive map of the fediverse years ago. You can see it [here](https://www.kumu.io/wakest/fediverse) tho its pretty badly done and really wrong and hasn't been updated in ages.

**Comment by brortao** [comment]
done! https://fediverse.space is just building the latest version; your instance will be on there momentarily :seedling:
