### ISSUE TITLE
Opt-in for pla.social

### ISSUE THREAD

**Issue by pla1** [brortao/fediverse.space#30]
I opt-in for crawling of pla.social for https://fediverse.space/

`No data
This instance has fewer than 5 users. It was not crawled in order to protect their privacy, but if it's your instance you can opt in.`

Thanks!

**Comment by brortao** [comment]
I added your instance to the whitelist, but the scraping failed. I think I know why:

fediverse.space scrapes `https://pla.social/api/v1/timelines/public?local=true` to gather statistics on how often users on instances interact with each other*.

It scrapes the most recent 5000 statuses, and attempts to do so in batches of 1000 statuses by adding `&limit=1000` to the endpoint. This returns an error on your instance, but with a lower limit it works fine. I'll lower this limit to something more reasonable. Apologies if fediverse.space has been causing unnecessary load on your instance!

\* This information is only saved in aggregate, e.g. "15 out of 100 statuses from pla.social mentioned someone on mastodon.social".

**Comment by pla1** [comment]
Thanks @brortao !

**Comment by pla1** [comment]
@brortao Some servers have a maximum cap on the quantity statuses that it will return. pla.social does not have a hard coded limit. It will try to deliver 1000. mastodon.social has a limit of 40 even when you request limit=1000. That explains why my server puked and others didn't. Thanks!

**Comment by brortao** [comment]
hey @pla1, sorry for the delay here.

even with a limit of 100, your server still returns a HTTP 500 error on many of the API loads. i've set the limit to 40, instead!

your instance is on fediverse.space now.
