### ISSUE TITLE
Opt-in for slime.dragon.garden

### ISSUE THREAD

**Issue by LadyLumb** [brortao/fediverse.space#41]
Hi I'm @Lumb@slime.dragon.garden and I'd like to opt in to be crawled if that's not a problem pls. <3

**Comment by brortao** [comment]
I added your instance to the whitelist, but the scraper ran into a few problems!

It looks like https://slime.dragon.garden/api/v1/instance/peers isn't an accessible endpoint -- fediverse.space uses this to help build its graph. Have you disabled this endpoint?

**Comment by brortao** [comment]
(The scraper shouldn't fail in that case, so I added an issue to track this: #45)

**Comment by LadyLumb** [comment]
That's strange. No, nothing is disabled, it's a regular ol vanilla install in every way tbh.

**Comment by brortao** [comment]
Interesting! I believe there's a setting called `peers_api_enabled` or "Publish list of discovered servers". Can you see if that's enabled on your instance?

**Comment by LadyLumb** [comment]
Ah okay that was disabled. I enabled it, that should fix, yeah?

**Comment by brortao** [comment]
Yes, your instance is on there now :)
